<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>User.Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" Version="14.0.0" />
      <PackageReference Include="MediatR.Contracts" Version="2.0.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Framework\Dal.Postgres\Dal.Postgres.csproj" />
      <ProjectReference Include="..\User.Application\User.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Identity\" />
    </ItemGroup>

</Project>
