<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Command\WorkoutPlan\AddWorkoutPlanToAnotherWard\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Workout.Domain\Workout.Domain.csproj" />
    </ItemGroup>

</Project>
